# Generated by Django 5.0.6 on 2024-07-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_answer', models.CharField(max_length=150)),
                ('correctness', models.BooleanField(default=False)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('access', models.IntegerField(choices=[(1, 'Студент'), (2, 'Преподаватель'), (3, 'Администратор')], default=1, verbose_name='access')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='IssuingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.option')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_group', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.answer')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='questions',
            field=models.ManyToManyField(to='Main.question'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lead_time', models.TimeField()),
                ('max_score', models.IntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.discipline')),
                ('questions', models.ManyToManyField(to='Main.question')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.test'),
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('option_question_number', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('lead_time', models.TimeField()),
                ('test_percentage', models.IntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.discipline')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.option')),
            ],
        ),
    ]
