# Generated by Django 4.2.13 on 2024-07-06 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0003_remove_question_answers_question_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'ответ', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'дисциплину', 'verbose_name_plural': 'дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='educationalgroup',
            options={'verbose_name': 'образовательную группу', 'verbose_name_plural': 'образовательные группы'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'вариант', 'verbose_name_plural': 'варианты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name': 'ответ на вопрос', 'verbose_name_plural': 'ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'результат теста', 'verbose_name_plural': 'результаты тестов'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access',
        ),
        migrations.AlterField(
            model_name='answer',
            name='correctness',
            field=models.BooleanField(default=False, verbose_name='корректность'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='possible_answer',
            field=models.CharField(max_length=150, verbose_name='вариант ответа'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationalgroup',
            name='number_group',
            field=models.CharField(max_length=50, verbose_name='номер группы'),
        ),
        migrations.AlterField(
            model_name='educationalgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='option',
            name='execution_status',
            field=models.BooleanField(default=False, verbose_name='статус выполнения'),
        ),
        migrations.AlterField(
            model_name='option',
            name='questions',
            field=models.ManyToManyField(to='Main.question', verbose_name='вопросы'),
        ),
        migrations.AlterField(
            model_name='option',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='option',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.test', verbose_name='тест'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фотография профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='Main.answer', verbose_name='ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0, verbose_name='количество баллов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.discipline', verbose_name='дисциплина'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lead_time',
            field=models.TimeField(verbose_name='время выполнения'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='количество баллов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='Main.question', verbose_name='вопросы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile', verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='option_question_number',
            field=models.IntegerField(default=1, verbose_name='номер вопроса в варианте'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='количество баллов'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.test', verbose_name='тест'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user_answer',
            field=models.CharField(max_length=150, verbose_name='ответ студента'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.discipline', verbose_name='дисциплина'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='lead_time',
            field=models.TimeField(verbose_name='время выполнения'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.option', verbose_name='вариант'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='количество баллов'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_percentage',
            field=models.IntegerField(default=0, verbose_name='процент выполнения'),
        ),
    ]
