# Generated by Django 4.2.13 on 2024-07-09 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_answer_options_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала'),
        ),
    ]
