# Generated by Django 4.2.13 on 2024-07-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_option_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswer',
            name='test',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.option', verbose_name='вариант'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('option', 'discipline')},
        ),
    ]
