# Generated by Django 4.2.13 on 2024-07-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_testanswer_test_testanswer_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalgroup',
            name='user',
        ),
        migrations.AddField(
            model_name='educationalgroup',
            name='user',
            field=models.ManyToManyField(to='Main.profile', verbose_name='студент'),
        ),
    ]
