# Generated by Django 4.2.13 on 2024-07-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_educationalgroup_user_educationalgroup_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name': 'ответ студента на вопрос', 'verbose_name_plural': 'ответы студента на вопросы'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='max_score',
        ),
    ]
